version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pet_db
      POSTGRES_USER: pet
      POSTGRES_PASSWORD: pet
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: pet_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
