#!/usr/bin/env bash
# =====================================================================
# setup.sh — one-time server setup for Dr. Gupet
#
#   sudo ./scripts/setup.sh --domain shop.example.com \
#        [--admin-domain admin.example.com] \
#        [--email you@example.com] \
#        [--phone 09120000000] \
#        [--with-front] [--skip-ssl]
#
# What it does (9 steps):
#   1) Check arguments
#   2) Enable swap on small VMs (< 2 GB RAM) so builds never stall
#   3) Install Docker, Docker Compose, nginx and certbot
#   4) Generate backend/.env with strong random secrets
#   5) Build the backend image and start the stack (MySQL + Redis + backend)
#   6) Wait for backend health (GET /api/v1/health)
#   7) Seed reference data + the admin user (ADMIN_SEED_PHONE)
#   8) Optional (--with-front): build frontend/ and admin/ (Node 20+)
#   9) Optional: activate SSL — skips cleanly when DNS is not ready
#
# Notes:
#   * Never prompts for input: safe to run unattended (nohup/tmux).
#   * Idempotent: an existing backend/.env is left untouched.
#   * The first backend image build can take 5-15 minutes on a 1 vCPU VM.
# =====================================================================
set -euo pipefail

# ---------- logging helpers ----------
if [[ -t 1 ]]; then
  G=$'\e[32m'; Y=$'\e[33m'; R=$'\e[31m'; B=$'\e[1m'; N=$'\e[0m'
else
  G=''; Y=''; R=''; B=''; N=''
fi
TOTAL_STEPS=9; STEP_NO=0
info()  { echo "${G}[✓]${N} $*"; }
step()  { STEP_NO=$((STEP_NO+1)); echo; echo "${B}[${STEP_NO}/${TOTAL_STEPS}]${N} $*"; }
warn()  { echo "${Y}[!]${N} $*"; }
die()   { echo "${R}[✗]${N} $*" >&2; exit 1; }
usage() { awk 'NR==1 {next} /^#/ {sub(/^# ?/,""); print; next} {exit}' "$0"; }

# ---------- 1) arguments ----------
if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then usage; exit 0; fi
step "Checking arguments"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
COMPOSE_FILE="$ROOT_DIR/backend/docker-compose.yml"
ENV_FILE="$ROOT_DIR/backend/.env"
ENV_EXAMPLE="$ROOT_DIR/backend/.env.example"

DOMAIN="" ADMIN_DOMAIN="" EMAIL="" PHONE="09120000000" WITH_FRONT=0 SKIP_SSL=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)       DOMAIN="${2:?}"; shift 2 ;;
    --admin-domain) ADMIN_DOMAIN="${2:?}"; shift 2 ;;
    --email)        EMAIL="${2:?}"; shift 2 ;;
    --phone)        PHONE="${2:?}"; shift 2 ;;
    --with-front)   WITH_FRONT=1; shift ;;
    --skip-ssl)     SKIP_SSL=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown argument: $1 (see --help)" ;;
  esac
done
[[ $EUID -eq 0 ]] || die "This script must run as root: sudo ./scripts/setup.sh"
[[ -n "$DOMAIN" || $SKIP_SSL -eq 1 ]] || warn "No --domain given — URLs in .env stay on example.com and SSL is skipped"

compose() { docker compose -f "$COMPOSE_FILE" "$@"; }

# ---------- 2) swap for small VMs ----------
step "Checking RAM / swap (1 GB VMs need swap for Docker + npm builds)"
MEM_KB="$(awk '/MemTotal/ {print $2}' /proc/meminfo)"
if [[ "$MEM_KB" -lt 2000000 ]] && ! swapon --show | grep -q .; then
  fallocate -l 1G /swapfile 2>/dev/null || dd if=/dev/zero of=/swapfile bs=1M count=1024 status=none
  chmod 600 /swapfile
  mkswap /swapfile >/dev/null
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
  info "1 GB swap enabled (RAM: $((MEM_KB/1024)) MB)"
else
  info "No swap change needed (RAM: $((MEM_KB/1024)) MB)"
fi

# ---------- 3) install Docker + nginx + certbot ----------
step "Installing Docker, Docker Compose, nginx and certbot"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq ca-certificates curl gnupg openssl nginx certbot python3-certbot-nginx

if ! command -v docker >/dev/null; then
  info "Installing Docker (official get.docker.com script)"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi
docker compose version >/dev/null 2>&1 \
  || apt-get install -y -qq docker-compose-plugin
info "Docker $(docker --version | cut -d' ' -f3 | tr -d ',') + Compose ready"

# ---------- 4) generate backend/.env ----------
step "Preparing backend/.env"
if [[ -f "$ENV_FILE" ]]; then
  warn "backend/.env already exists — left untouched (edit it manually if needed)"
else
  cp "$ENV_EXAMPLE" "$ENV_FILE"

  JWT_ACCESS_SECRET="$(openssl rand -hex 32)"
  JWT_REFRESH_SECRET="$(openssl rand -hex 32)"
  OTP_HASH_SECRET="$(openssl rand -hex 32)"
  MYSQL_PASSWORD="$(openssl rand -hex 16)"
  MYSQL_ROOT_PASSWORD="$(openssl rand -hex 16)"

  sed -i \
    -e "s|^JWT_ACCESS_SECRET=.*|JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET|" \
    -e "s|^JWT_REFRESH_SECRET=.*|JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET|" \
    -e "s|^OTP_HASH_SECRET=.*|OTP_HASH_SECRET=$OTP_HASH_SECRET|" \
    -e "s|^ADMIN_SEED_PHONE=.*|ADMIN_SEED_PHONE=$PHONE|" \
    "$ENV_FILE"

  # MySQL passwords for interpolation in docker-compose.yml
  cat >> "$ENV_FILE" <<EOF

# --- generated by scripts/setup.sh ---
MYSQL_PASSWORD=$MYSQL_PASSWORD
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
EOF

  if [[ -n "$DOMAIN" ]]; then
    ORIGINS="https://$DOMAIN"
    [[ -n "$ADMIN_DOMAIN" ]] && ORIGINS="$ORIGINS,https://$ADMIN_DOMAIN"
    sed -i \
      -e "s|^PUBLIC_BASE_URL=.*|PUBLIC_BASE_URL=https://$DOMAIN|" \
      -e "s|^CORS_ORIGINS=.*|CORS_ORIGINS=$ORIGINS|" \
      -e "s|^PAYMENT_CALLBACK_URL=.*|PAYMENT_CALLBACK_URL=https://$DOMAIN/api/v1/payments/callback|" \
      -e "s|^FRONTEND_PAYMENT_RESULT_URL=.*|FRONTEND_PAYMENT_RESULT_URL=https://$DOMAIN/payment/result|" \
      "$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE"
  info "backend/.env created (strong secrets generated; readable by owner only)"
fi

mkdir -p "$ROOT_DIR/backend/uploads"

# ---------- 5) build image + start stack ----------
step "Building the backend image and starting MySQL + Redis + backend"
info "First build takes a while on small VMs — progress below is normal, it is NOT stuck"

info "Pulling base images (mysql:8.4, redis:7-alpine) with retries..."
PULLED=0
for attempt in 1 2 3; do
  if compose pull mysql redis; then PULLED=1; break; fi
  warn "Image pull failed (attempt $attempt/3) — retrying in 10s..."
  sleep 10
done
if [[ $PULLED -eq 0 ]]; then
  warn "Could not pull images from Docker Hub (403/timeouts are usually network restrictions)."
  warn "Fixes (pick one, then re-run this script):"
  warn "  1) Configure a registry mirror in /etc/docker/daemon.json and 'systemctl restart docker'"
  warn "     (see DEPLOY.md, section 'Docker Hub blocked (403)')"
  warn "  2) Load the images from a machine that can reach Docker Hub: docker save | docker load"
  die "docker compose pull failed for mysql/redis"
fi

compose build backend
compose up -d
info "Stack is up"

# ---------- 6) wait for backend health ----------
step "Waiting for backend health (GET /api/v1/health)"
for i in $(seq 1 90); do
  if curl -fsS --max-time 3 http://127.0.0.1:3000/api/v1/health >/dev/null 2>&1; then
    info "Backend is healthy"
    break
  fi
  if [[ $i -eq 90 ]]; then
    die "Backend did not become healthy — check: docker compose -f backend/docker-compose.yml logs backend"
  fi
  [[ $((i % 10)) -eq 0 ]] && warn "Still waiting... ($((i*3))s) — first boot runs migrations"
  sleep 3
done

# ---------- 7) seed ----------
step "Seeding reference data + admin user (ADMIN_SEED_PHONE)"
compose exec -T backend npm run prisma:seed || warn "Seed failed — run it later: docker compose -f backend/docker-compose.yml exec backend npm run prisma:seed"

# ---------- 8) optional frontend builds ----------
if [[ $WITH_FRONT -eq 1 ]]; then
  step "Building frontend/dist and admin/dist (Node 20+)"
  if command -v npm >/dev/null; then
    export NODE_OPTIONS=--max-old-space-size=768
    info "Building frontend..."
    (cd "$ROOT_DIR/frontend" && npm ci --no-audit --no-fund && npm run build)
    info "Building admin panel..."
    (cd "$ROOT_DIR/admin" && npm ci --no-audit --no-fund && npm run build)
    info "frontend/dist and admin/dist are ready"
  else
    warn "npm not found — build the frontends later (or in CI) and re-run scripts/ssl.sh"
  fi
else
  step "Skipping frontend builds (use --with-front to build them here)"
fi

# ---------- 9) optional SSL ----------
if [[ $SKIP_SSL -eq 1 || -z "$DOMAIN" ]]; then
  step "Skipping SSL"
  [[ $SKIP_SSL -eq 1 ]] && warn "SSL skipped by request — later: sudo ./scripts/ssl.sh --domain $DOMAIN"
else
  step "Activating SSL (skips cleanly if DNS is not ready yet)"
  SSL_ARGS=(--domain "$DOMAIN" --root "$ROOT_DIR")
  [[ -n "$ADMIN_DOMAIN" ]] && SSL_ARGS+=(--admin-domain "$ADMIN_DOMAIN")
  [[ -n "$EMAIL" ]] && SSL_ARGS+=(--email "$EMAIL")
  "$ROOT_DIR/scripts/ssl.sh" "${SSL_ARGS[@]}" \
    || warn "SSL activation failed — fix the issue and re-run: sudo ./scripts/ssl.sh --domain $DOMAIN"
fi

echo
info "Setup finished ✅"
echo "  ${B}Status:${N}   cd $ROOT_DIR && docker compose -f backend/docker-compose.yml ps"
echo "  ${B}Logs:${N}     docker compose -f backend/docker-compose.yml logs -f backend"
echo "  ${B}Update:${N}   sudo $ROOT_DIR/scripts/update.sh"
echo "  ${B}Guide:${N}    $ROOT_DIR/DEPLOY.md"
